# Generated by Django 3.1.1 on 2020-12-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='avail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('date', models.IntegerField()),
                ('start', models.CharField(max_length=12)),
                ('end', models.CharField(max_length=12)),
                ('status', models.IntegerField()),
                ('cn', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meetingid', models.IntegerField(blank=True, null=True)),
                ('joinurl', models.TextField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.IntegerField(blank=True, null=True)),
                ('orderid', models.CharField(blank=True, max_length=255, null=True)),
                ('qurl', models.TextField(blank=True, null=True)),
                ('curl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='recur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.IntegerField()),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start', models.CharField(max_length=12)),
                ('length', models.IntegerField()),
            ],
        ),
    ]
