# Generated by Django 3.1.5 on 2021-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwards',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
