# Generated by Django 3.1.5 on 2021-03-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_forwards_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='forwards',
            name='link',
            field=models.CharField(default='http://www.thequadco.com', max_length=255),
        ),
    ]
