# Generated by Django 3.1.1 on 2020-12-30 19:22

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('bcn', models.AutoField(primary_key=True, serialize=False)),
                ('bn', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Published'), (0, 'Hidden')])),
                ('author', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('bn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Published'), (0, 'Hidden')])),
                ('author', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
