# Generated by Django 3.1.1 on 2020-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Colton Hail', max_length=255),
            preserve_default=False,
        ),
    ]
