# Generated by Django 3.1.1 on 2021-01-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qregstr',
            name='assigned',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
