# Generated by Django 3.1.5 on 2021-03-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='link',
            field=models.CharField(default='http://www.thequadco.com', max_length=255),
        ),
    ]
