# Generated by Django 3.1.5 on 2021-03-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20210313_1357'),
    ]

    operations = [
        migrations.DeleteModel(
            name='passwordreset',
        ),
    ]
