# Generated by Django 3.1.5 on 2021-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_delete_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='passwordreset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('requestsent', models.IntegerField(default=0)),
                ('codestr', models.CharField(max_length=20)),
                ('requesttime', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(default='http://www.thequadco.com', max_length=255)),
            ],
        ),
    ]
