# Generated by Django 3.1.1 on 2021-01-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
