# Generated by Django 3.1.1 on 2020-11-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_auto_20201014_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='qinfo',
            name='cost',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='qinfo',
            name='email',
            field=models.CharField(default='example@gmail.com', max_length=255),
        ),
    ]
