# Generated by Django 3.1.1 on 2020-11-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0008_auto_20201121_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qinfo',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Dr.', 'Dr.')], max_length=255),
        ),
        migrations.AlterField(
            model_name='qinfo',
            name='qn',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='qinfo',
            name='suffix',
            field=models.CharField(blank=True, choices=[('PhD', 'PhD'), ('M.D.', 'M.D.')], max_length=255),
        ),
    ]
