# Generated by Django 3.1.1 on 2020-12-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0010_auto_20201206_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qinfo',
            name='active',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1),
        ),
    ]
