# Generated by Django 3.1.1 on 2020-12-06 16:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('bn', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'Published'), (0, 'Hidden')])),
                ('author', models.IntegerField()),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
