# Generated by Django 3.1.1 on 2020-09-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qinfo',
            fields=[
                ('qn', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.')], max_length=255)),
                ('first', models.CharField(max_length=255)),
                ('last', models.CharField(max_length=255)),
                ('suffix', models.CharField(blank=True, choices=[('phd', 'PhD'), ('md', 'M.D.')], max_length=255)),
                ('category', models.CharField(choices=[('medicine', 'Medicine')], max_length=255)),
                ('servicelinedev', models.IntegerField()),
                ('capitalplan', models.IntegerField()),
                ('pysicianrecruitment', models.IntegerField()),
                ('processimprove', models.IntegerField()),
                ('productivity', models.IntegerField()),
                ('operationsfinance', models.IntegerField()),
                ('leadingmeetings', models.IntegerField()),
                ('dataanalysis', models.IntegerField()),
                ('teamcourses', models.IntegerField()),
                ('personalleadership', models.IntegerField()),
                ('personalitytypes', models.IntegerField()),
                ('tempassignments', models.IntegerField()),
                ('special1', models.CharField(max_length=255)),
                ('special2', models.CharField(max_length=255)),
                ('special3', models.CharField(max_length=255)),
                ('special4', models.CharField(max_length=255)),
                ('special5', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('linkedin', models.TextField()),
                ('yearexp', models.IntegerField()),
            ],
        ),
    ]
