# Generated by Django 3.1.1 on 2020-10-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_clientprofiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofiles',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='clientprofiles',
            name='email_validated',
        ),
    ]
