# Generated by Django 3.1.1 on 2020-10-31 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlogin', '0004_auto_20201031_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientprofile',
            fields=[
                ('cn', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='clientprofiles',
        ),
    ]
