# Generated by Django 3.1.1 on 2020-10-31 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20201031_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='cn',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
