# Generated by Django 3.1.1 on 2020-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_qphoto_pid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qstripe',
            fields=[
                ('qn', models.IntegerField(primary_key=True, serialize=False)),
                ('acct_id', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
