# Generated by Django 3.1.1 on 2020-11-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0009_qstripe'),
    ]

    operations = [
        migrations.CreateModel(
            name='QregStr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('assigned', models.IntegerField(blank=True)),
            ],
        ),
    ]
